name: Deploy to VPS

on:
    push:
        branches: [ 'master' ]
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    registry: docker.io
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_TOKEN }}

            -   name: Build and push
                uses: docker/build-push-action@v5
                with:
                    context: .
                    file: ./docker/Dockerfile
                    push: true
                    tags: |
                        francoisvid/portfolio:latest
                        francoisvid/portfolio:${{ github.sha }}

            -   name: Deploy to VPS
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.VPS_HOST }}
                    username: ${{ secrets.VPS_USERNAME }}
                    key: ${{ secrets.SSH_KEY }}
                    script: |
                        cd /opt/portfolio
                        docker compose pull portfolio
                        docker compose up -d portfolio
